## An array of random numbers 
-  random array is an array containing values generated randomly using NumPy’s random module.
- * np.random.rand() → random decimal numbers
- * np.random.randint() → random integer numbers

In [1]:
# random
# randn
# randint

In [1]:
import numpy as np

In [11]:
np.random.random(10) # Always Positive between 0 to 1

array([0.21982799, 0.49097747, 0.9461492 , 0.15577095, 0.5815218 ,
       0.18884776, 0.66969251, 0.573766  , 0.43041744, 0.78271328])

In [8]:
np.random.randint(1,100,5) # Need to give range and how many elements you want

array([69,  6, 18, 63, 48])

In [9]:
np.random.randn(10) # Random values between -3 to +3

array([ 0.27217404, -0.83311678, -0.87651892,  0.73025357,  0.73700204,
       -1.22400333,  1.00531392,  0.81665479,  1.40863536,  0.03116091])

## 1) Operations on a 1D Array

- 1)Addition
- 2)Multiplication
- 3)Comparison

In [12]:
# 1)Addition
l1 = np.array([1,2,3,4])
l2 = np.array([11,12,13,14])
l1+l2

array([12, 14, 16, 18])

In [13]:
# 2)Substraction
l1 = np.array([1,2,3,4])
l2 = np.array([11,12,13,14])
l1-l2

array([-10, -10, -10, -10])

In [3]:
# 3)Multiplication
l1 = np.array([1,2,3,4])
l2 = np.array([11,12,13,14])
l1*l2

array([11, 24, 39, 56])

In [15]:
# Note :- Array size is different , operations are not possible

## Broadcasting :- Update the main Array

In [17]:
# Broadcasting
l1+10

array([11, 12, 13, 14])

In [18]:
l1-1

array([0, 1, 2, 3])

In [19]:
l1*10

array([10, 20, 30, 40])

## Comparision (Conditional Formatting)

In [7]:
l2

array([11, 12, 13, 14])

In [8]:
l2>13

array([False, False, False,  True])

In [10]:
l2[l2>12]

array([13, 14])

In [16]:
l2%2==0

array([False,  True, False,  True])

In [12]:
l2[l2%2==0]

array([12, 14])

In [21]:
# Practice
#1) 
l1 = [1,2,3,4]
l2 = [4,5,6,7]
l1 = np.array(l1)
l1



array([1, 2, 3, 4])

In [22]:
l2 = np.array(l2)
l2


array([4, 5, 6, 7])

In [23]:
# do the element wise division
l1/l2

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [26]:
# 2) Filter the odd values in the array 1-10 (using conditional formatting)
l3 = np.array([1,2,3,4,5,6,7,8,9,10])
l3[l3%2!=0]

array([1, 3, 5, 7, 9])

## Operations on a 2D Array

- 1) Addition
- 2) Multiplication
- 3) Comparision
- 4) matrix multiplication
- 5) Transpose

In [27]:
l1 = np.arange(1,5,1).reshape(2,2)
l2 = np.arange(5,9,1).reshape(2,2)
print(l1)
print(l2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [28]:
l1+l2

array([[ 6,  8],
       [10, 12]])

In [29]:
l1-l2

array([[-4, -4],
       [-4, -4]])

In [30]:
l1/l2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [31]:
l1*l2

array([[ 5, 12],
       [21, 32]])

In [32]:
l1@l2 # Matrix Multiplication

array([[19, 22],
       [43, 50]])

In [34]:
np.matmul(l1,l2) # Matrix Multiplication

array([[19, 22],
       [43, 50]])

## Comparision (Conditional Formatting)

In [35]:
l1

array([[1, 2],
       [3, 4]])

In [36]:
l1>2

array([[False, False],
       [ True,  True]])

In [37]:
l1[l1>2]

array([3, 4])

In [39]:
l1

array([[1, 2],
       [3, 4]])

In [38]:
# Transpose 

l1.T

array([[1, 3],
       [2, 4]])

In [50]:
# Practice

l1 = np.eye(3, 3)
l2 = np.array([[1, 2, 0],
               [3, 4, 0],
               [5, 6, 0]])

np.matmul(l1, l2)

np.matmul(l1, l2)

array([[1., 2., 0.],
       [3., 4., 0.],
       [5., 6., 0.]])

In [48]:
l1*l2 # Normal Multiplication

array([[1., 0., 0.],
       [0., 4., 0.],
       [0., 0., 0.]])

## Arithmetic Functions in Numpy
- 1) Sum
- 2) min
- 3) max
- 4) sort

In [2]:
l1 = np.arange(1,10,1)
l1.sum()

np.int64(45)

In [3]:
np.min(l1)

np.int64(1)

In [4]:
np.max(l1)

np.int64(9)

In [5]:
l1.sort()
print(l1)

[1 2 3 4 5 6 7 8 9]


In [6]:
# 2D array


In [7]:
l1 =np.arange(1,10,1).reshape(3,3)
print(l1)
l1.sum(axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [8]:
l1.sum(axis = 1)

array([ 6, 15, 24])

In [10]:
l1.sum()

np.int64(45)

In [9]:
# axis = 0 -> vertical direction
# axis = 1 -> horizontal direction

In [11]:
l1.min(axis = 0)

array([1, 2, 3])

In [12]:
l1.min(axis = 1)

array([1, 4, 7])

In [13]:
l1.max(axis = 0)

array([7, 8, 9])

In [14]:
l1.max(axis = 1)

array([3, 6, 9])

In [17]:
# Practice

l1 =np.arange(11,20,1).reshape(3,3)
l1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [18]:
l1.sum()

np.int64(135)

In [19]:
l1.min()

np.int64(11)

In [20]:
l1.max()

np.int64(19)

In [21]:
l1.sum(axis=0)

array([42, 45, 48])

In [22]:
l1.min(axis=0)

array([11, 12, 13])

In [23]:
l1.max(axis=0)

array([17, 18, 19])

In [24]:
l1.sum(axis=1)

array([36, 45, 54])

In [25]:
l1.min(axis=1)

array([11, 14, 17])

In [26]:
l1.max(axis=1)

array([13, 16, 19])

In [30]:
l1.sort()
print(l1)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
