## What is Python Numpy?
- NumPy (short for Numerical Python) is a popular Python library used for fast numerical calculations, especially with arrays and matrices.

- The main feature of NumPy is the ndarray, which is similar to a Python list but optimized for mathematical operations.

- NumPy is commonly used for arrays and matrices, statistics, linear algebra, scientific calculations, and data analysis. Libraries such as Pandas, SciPy, and many machine-learning tools also build on NumPy.

- In simple terms: Python is the programming language; NumPy is a library that makes numerical and array-based calculations much easier and faster.

In [2]:
import numpy as np


In [7]:
age = np.array([1,2,3,4,5,6,5,7,False])
print(age)

[1 2 3 4 5 6 5 7 0]


In [8]:
age = np.array(["1",2,3,4,5,5.5,6,7,8])
print(age)

['1' '2' '3' '4' '5' '5.5' '6' '7' '8']


In [9]:
age = np.array([1,2,3,4,5,5.5,6,7,8])
print(age)

[1.  2.  3.  4.  5.  5.5 6.  7.  8. ]


In [16]:
# Practice

l1 = [1,2,3,4,"Hello"] 
l2 = np.array(l1)
print("Array :",l2)
l2

Array : ['1' '2' '3' '4' 'Hello']


array(['1', '2', '3', '4', 'Hello'], dtype='<U21')

## Attributes and functions

Attribute

Meaning

Example

ndim

Number of dimensions

a.ndim

shape

Size of each dimension

a.shape

size

Total number of elements

a.size

dtype

Data type of elements

a.dtype

itemsize

Memory size of one element in bytes

a.itemsize

nbytes

Total memory used by array

a.nbytes

In [ ]:
data = np.array([1,2,3,4,5,6,7])
print(data.ndim) # number of dimensions
print(data.size) # no of elements inside the array
print(data.shape) # Shape of the array
print(data.dtype) # Data type of the elements

1
7
(7,)
int64


In [19]:
# practice:
# create an array -[10,11,12,14]

data1 = np.array([10,11,12,14])
print(data1.ndim) # number of dimensions
print(data1.size) # no of elements inside the array
print(data1.shape) # Shape of the array
print(data1.dtype) # Data type of the elements

1
4
(4,)
int64


In [20]:
# 1 dimension
np.array([1,2,3,45])

array([ 1,  2,  3, 45])

In [ ]:
# 2 dimension / matrix
data2 = np.array([[1,2,3,4],
                  [5,6,7,8]])
print(data2.ndim) # number of dimensions
print(data2.size) # no of elements inside the array
print(data2.shape) # Shape of the array
print(data2.dtype) # Data type of the elements

2
8
(2, 4)
int64


In [28]:
data3 = np.array([[10,11,12,13],
                  [14,15,16,17]])
print(data3.ndim) # number of dimensions
print(data3.size) # no of elements inside the array
print(data3.shape) # Shape of the array
print(data3.dtype) # Data type of the elements

2
8
(2, 4)
int64


In [29]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

## Functions

- 1  np.arange()

Creates an array with a sequence of numbers.

In [31]:
d1 = np.arange(0,11,2)
d1

array([ 0,  2,  4,  6,  8, 10])

In [32]:
d1 = np.arange(1,11,1)
d1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
d1 = np.arange(0,11,2.5)
d1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
list(range(0,11,2.5)) # In array possible

TypeError: 'float' object cannot be interpreted as an integer

In [35]:
# Practice :
# 1) Create an array even elements 1-200
d1 = np.arange(0,201,2)
print("Even nu is :",d1)

Even nu is : [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200]


In [37]:
# 2) np.arrange(2,20,3)
d2 =  np.arange(2,20,3)
d2

array([ 2,  5,  8, 11, 14, 17])

In [3]:
# 3dimension / tensors

# 3d = [blocks1,block2]
# block =[row and columns]

b1 = np.array([[1,2,3,4],[5,6,7,8]])
b2 = np.array([[9,10,11,12],[13,14,15,16]])
blocks = [b1,b2]
d3 = np.array(blocks)
d3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [4]:
print(d3.ndim) # number of dimensions
print(d3.size) # no of elements inside the array
print(d3.shape) # Shape of the array
print(d3.dtype) # Data type of the elements

3
16
(2, 2, 4)
int64


In [5]:
# shape (blocks,rows,columns)

- reshape
- reshapes the rows and columns of the array

In [6]:
# Syntax:

In [7]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data.size)
print(data.shape)


10
(10,)


In [8]:
data.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
data.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
data = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
data = np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)
data

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
np.arange(1,13).reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
# Practice

# Create an array 1-30 and reshape

#1) 6,5

d4=np.arange(1,31).reshape(6,5)
d4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
#2) 2,3,5
d4 = np.arange(1,31).reshape(2,3,5)
d4

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [21]:
#3) 6,6
d4 = np.arange(1,31).reshape(6,6)
d4

ValueError: cannot reshape array of size 30 into shape (6,6)

In [22]:
#4) 5,3,2
d4 = np.arange(1,31).reshape(5,3,2)
d4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]]])

In [23]:
print(d4.ndim) # number of dimensions
print(d4.size) # no of elements inside the array
print(d4.shape) # Shape of the array
print(d4.dtype) # Data type of the elements

3
30
(5, 3, 2)
int64


Zeros,Ones and Identity matrix

In [27]:
# Syntax:
# arr_name = np.zeros([dimension])

data = np.zeros([3,5])
data

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
# Syntax:
# arr_name = np.ones([dimension])

data = np.ones([3,5])
data

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# eye - identity matrix
# Syntax :
# np.eye(n,dimension) # row count = column count

np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Practice :
# 1) create (5,4) ones and reshape them to (4,5)
data = np.ones([5,4]).reshape(4,5)
data

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
#2) create an identity matrix of 5 dimension
data = np.eye(5,5)
print(data)
data.dtype


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')

In [35]:
data = np.eye(5,5,dtype="int")
print(data)
data.dtype

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


dtype('int64')

In [36]:
data = np.eye(5,5,dtype = "complex")
print(data)
data.dtype

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


dtype('complex128')

## Indexing Array
## Slicing Array

In [37]:
# 1d array
data = np.arange(1,10,1)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Indexing
data[7]

np.int64(8)

In [ ]:
# Slicing
data[0:9:2] # In array start with 2 num

array([1, 3, 5, 7, 9])

In [41]:
data[1:9:2]

array([2, 4, 6, 8])

In [42]:
data[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# 2d array
data = np.arange(1,21,1).reshape(2,10)
data


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [45]:
data[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
data[1,1]

np.int64(12)

In [52]:
data[0:1:1]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [53]:
data[1:2:1]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [56]:
data[::,0:5:1]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [57]:
data[0:1:1,0:5:1]

array([[1, 2, 3, 4, 5]])

In [59]:
data[0:2:1,0:10:2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

## An array of random numbers 
-  random array is an array containing values generated randomly using NumPy’s random module.
- * np.random.rand() → random decimal numbers
- * np.random.randint() → random integer numbers

In [61]:
# random
# randn
# randint

## Filtering : arr_name[arr_name with condition]