## Concatenation of an Array

### Vertical Concatenaton
- Syntax :- np.concat(list/tuple of array,axis=0)
- np.vstack(list of array)

- condition:
- 1)column count needs to be equal

In [1]:
import numpy as np
arr1 =np.arange(1,10,1).reshape(3,3)
arr2 = np.arange(11,20,1).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [2]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [5]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Horizontal Concatenation

- Syntax :- np.concat(list/tuple of array,axis=1)
- np.hstack(list of array)

- condition:
- 1)rows count needs to be equal


In [6]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [8]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [ ]:
# practice :
# 1) Conatenate 2*3 , 4*3 array  using axis = 0
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(11,23,1).reshape(4,3)
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [ ]:
#2 Conatenate 2*3 , 2*3 array  using axis = 1
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(11,17,1).reshape(2,3)
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
# 3 Conatenate 2*3 , 2*3 array  using axis = 0
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(11,17,1).reshape(2,3)
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [ ]:
# 4 Conatenate 2*3 , 4*3 array  using axis = 1
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(11,23,1).reshape(4,3)
np.concatenate([arr1,arr2],axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

## Split

#### hsplit - draw a vertical line to split them equally
#### vsplit - draw a horizontal line to split them equally

- Syntax : np.vsplit(array,no of equal split)
- Syntax : np.hsplit(array,no of equal split)

In [15]:
arr1 = np.arange(1,10,1).reshape(3,3)
np.vsplit(arr1,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [16]:
np.hsplit(arr1,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [17]:
arr2 = np.arange(1,17,1).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
np.vsplit(arr2,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [19]:
np.vsplit(arr2,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [20]:
np.hsplit(arr2,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [21]:
np.hsplit(arr2,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [ ]:
# Practice
# 1) Concatenate 2*3 and 5*3 using vstack
arr1 = np.arange(1,7,1).reshape(2,3)
arr2 = np.arange(1,16,1).reshape(5,3)
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
# 2) Concatenate 5*4 and 5*3 using hstack
arr1 = np.arange(1,21,1).reshape(5,4)
arr2 = np.arange(1,16,1).reshape(5,3)
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  4,  1,  2,  3],
       [ 5,  6,  7,  8,  4,  5,  6],
       [ 9, 10, 11, 12,  7,  8,  9],
       [13, 14, 15, 16, 10, 11, 12],
       [17, 18, 19, 20, 13, 14, 15]])

In [ ]:
# 3) Split 4*4 array into 2 arrays using vsplit
arr1 = np.arange(1,17,1).reshape(4,4)
np.hsplit(arr1,2)


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
# 4) Split 4*4 array into 4 arrays using vsplit
arr1 = np.arange(1,17,1).reshape(4,4)
np.vsplit(arr1,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

### Iterating Array

- Syntax : np.nditer(array_name)

In [28]:
arr1 = np.arange(1,10)
print(arr1)
for i in np.nditer(arr1):
    print(i)


[1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9


In [29]:
a1 = np.arange(1,10).reshape(3,3)

for i in np.nditer(a1):
               print(i)

1
2
3
4
5
6
7
8
9


In [30]:
a1 = np.arange(1,10).reshape(3,3)

for i in a1:
               print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [32]:
a1 = np.arange(1,10).reshape(3,3)

for i in np.nditer(a1):
               if i%2 == 0:
                              print("Even :",i)
               else:
                              print("Odd :",i)

Odd : 1
Even : 2
Odd : 3
Even : 4
Odd : 5
Even : 6
Odd : 7
Even : 8
Odd : 9


In [34]:
# Create 2D array of random numbers and print even and odd numbers from it.
a1 = np.random.randint(1,10,9).reshape(3,3)
print(a1)
for i in np.nditer(a1):
               if i%2 == 0:
                              print("Even :",i)
               else:
                              print("Odd :",i)

[[2 7 4]
 [8 3 2]
 [4 2 6]]
Even : 2
Odd : 7
Even : 4
Even : 8
Odd : 3
Even : 2
Even : 4
Even : 2
Even : 6


In [ ]:
# Create 2D array of random numbers and print even and odd numbers from it.
a1 = np.random.randint(1,10,size=(3,3,3))

for i in np.nditer(a1):
               if i%2 == 0:
                              print("Even :",i)
               else:
                              print("Odd :",i)

Odd : 5
Odd : 5
Even : 8
Odd : 9
Even : 8
Odd : 5
Even : 2
Even : 4
Odd : 1
Even : 2
Even : 2
Even : 6
Even : 8
Even : 6
Even : 8
Odd : 1
Even : 4
Even : 8
Even : 6
Odd : 5
Odd : 3
Even : 8
Even : 2
Odd : 5
Even : 2
Even : 2
Even : 8


In [44]:
a1 = np.random.randint(1,10,27).reshape(3,3,3)
print(a1)
print()
for i in np.nditer(a1):
               if i%2 == 0:
                              print("Even :",i)
               else:
                              print("Odd :",i)

[[[9 3 3]
  [5 7 5]
  [5 5 6]]

 [[1 6 9]
  [6 8 8]
  [7 1 9]]

 [[1 1 1]
  [8 7 1]
  [7 1 6]]]

Odd : 9
Odd : 3
Odd : 3
Odd : 5
Odd : 7
Odd : 5
Odd : 5
Odd : 5
Even : 6
Odd : 1
Even : 6
Odd : 9
Even : 6
Even : 8
Even : 8
Odd : 7
Odd : 1
Odd : 9
Odd : 1
Odd : 1
Odd : 1
Even : 8
Odd : 7
Odd : 1
Odd : 7
Odd : 1
Even : 6


In [45]:
a1 = np.array([[1,2],[3,4]])
for i in np.nditer(a1,order = 'F'):
               print(i)

1
3
2
4


In [48]:
a1 = np.random.randint(1,10,27).reshape(3,3,3)
for i in np.nditer(a1,order = 'F'):
               print(i)

2
8
2
1
8
7
7
5
5
7
9
4
5
7
7
5
3
7
1
5
1
9
9
7
1
4
2


## Frequently used functions (Generic Funcions)

In [49]:
# Mean , Median
a1 = np.random.randint(1,10,5)
print(a1)

[9 4 7 8 7]


In [51]:
np.mean(a1)

np.float64(7.0)

In [52]:
np.median(a1)

np.float64(7.0)

In [53]:
# std,var
np.std(a1)

np.float64(1.6733200530681511)

In [54]:
np.var(a1)

np.float64(2.8)

In [55]:
# log , Exponential
np.log(a1)

array([2.19722458, 1.38629436, 1.94591015, 2.07944154, 1.94591015])

In [56]:
np.exp(a1)

array([8103.08392758,   54.59815003, 1096.63315843, 2980.95798704,
       1096.63315843])

In [89]:
# Flatten  - Multiple dimensions to single dimension
a1= np.arange(1,10,1).reshape(3,3)
a1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# linspace - 1D array with equal intervals
# np.linespace(start,stop,no of values)
np.linspace(1,9,3)

array([1., 5., 9.])

In [65]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [66]:
# argmax
# argmin
# argsort()


In [67]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.argmax(a1)

np.int64(8)

In [69]:
np.argmin(a1)

np.int64(0)

In [75]:
a2 = np.array([55,4,3,1,2])
index = np.argsort(a2) # Takes only 1D array and returns the index of sorted array.
index

array([3, 4, 2, 1, 0])

In [76]:
a2[index]

array([ 1,  2,  3,  4, 55])

In [90]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
a1.dtype

dtype('int64')

In [86]:
# astype
# Syntax :- array.astype(dtype)

a1 = a1.astype(np.float64)
a1


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [87]:
a1.dtype


dtype('float64')

In [3]:
# Add values using index 
# Syntax = array[index] = value

arr1 =np.arange(1,10,1)

print(arr1)
arr1[0]=100
print(arr1)
arr1[10]=200
print(arr1)

[1 2 3 4 5 6 7 8 9]
[100   2   3   4   5   6   7   8   9]


IndexError: index 10 is out of bounds for axis 0 with size 9

In [4]:
# insert
# Syntax :- np.insert(array,index,value,axis)

arr1 =np.arange(1,10,1)
np.insert(arr1,7,200)

array([  1,   2,   3,   4,   5,   6,   7, 200,   8,   9])

In [7]:
arr1 =np.arange(1,10,1).reshape(3,3)
print(arr1)
np.insert(arr1,1,200,axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[  1,   2,   3],
       [200, 200, 200],
       [  4,   5,   6],
       [  7,   8,   9]])

In [9]:
# append :-
# Syntax :- np.append(array,value,axis)
print(arr1)
np.append(arr1,200)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 200])

In [10]:
# delete
# Syntax :- np.delete(array,index,axis)

np.delete(arr1,0)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr2 = np.arange(1,10,1).reshape(3,3)

np.delete(arr2,0,axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Where
# Syntax :- np.where(condition,x,y)

np.where(arr1>5,arr1,0)
np.where(arr1>5,"Yes","No")

array([['No', 'No', 'No'],
       ['No', 'No', 'Yes'],
       ['Yes', 'Yes', 'Yes']], dtype='<U3')

In [22]:
np.where((arr1>2) & (arr1<6),arr1,0)


array([[0, 0, 3],
       [4, 5, 0],
       [0, 0, 0]])

In [23]:
np.where((arr1>2) | (arr1<6),arr1,0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# any
# Syntax :- array.any(axis=None,out=None,keepdims=False)

np.array([True,True,False]).any()

np.True_

In [25]:
np.array([False,False]).any()

np.False_

In [26]:
# all
# syntax :- array.all(axis=None,out=None,keepdims=False)
np.array([True,True,True]).all()

np.True_

In [27]:
np.array([True,True,False]).all()

np.False_